"""
Processed dataset data structures.

These dataclasses describe the optimized dataset generated by the
preprocessing stage.

Unlike the raw types, these structures represent metadata about the
compiled dataset rather than the original EVIMO2 files.

Large arrays such as

- event indices
- motion indices
- object states
- verification results

are stored separately as NumPy files and accessed by the loader.

Nothing in this file should contain large arrays.
"""

from __future__ import annotations

from dataclasses import dataclass


# =============================================================================
# Event Window
# =============================================================================

@dataclass(frozen=True, slots=True)
class EventWindow:
    """
    Event slice corresponding to one processed frame.

    Parameters
    ----------
    start_idx
        Inclusive start index into the event array.

    end_idx
        Exclusive end index into the event array.

    start_time
        Timestamp of the first event.

    end_time
        Timestamp of the last event.
    """

    start_idx: int
    end_idx: int

    start_time: float
    end_time: float

    @property
    def num_events(self) -> int:
        """Number of events in this window."""
        return self.end_idx - self.start_idx


# =============================================================================
# Motion Metrics
# =============================================================================

@dataclass(frozen=True, slots=True)
class MotionMetrics:
    """
    Sequence-level motion statistics for one object.

    These statistics are computed during preprocessing and are primarily
    used for verification and dataset analysis.
    """

    mean_translation: float
    max_translation: float

    mean_rotation: float
    max_rotation: float

    is_dynamic: bool


# =============================================================================
# Processed Object
# =============================================================================

@dataclass(frozen=True, slots=True)
class ProcessedObject:
    """
    Metadata describing one processed object.

    Parameters
    ----------
    object_id
        Unique object identifier.

    name
        Human-readable object name.

    motion
        Motion statistics computed during preprocessing.

    first_frame
        First frame where the object appears.

    last_frame
        Last frame where the object appears.

    visible_frames
        Number of frames where the object is visible.
    """

    object_id: int

    name: str

    motion: MotionMetrics

    first_frame: int
    last_frame: int

    visible_frames: int


# =============================================================================
# Processed Frame
# =============================================================================

@dataclass(frozen=True, slots=True)
class ProcessedFrame:
    """
    Metadata describing one processed frame.

    Parameters
    ----------
    frame_id
        Sequential frame index.

    timestamp
        Ground-truth timestamp.

    event_window
        Event slice corresponding to this frame.
    """

    frame_id: int

    timestamp: float

    event_window: EventWindow


# =============================================================================
# Processed Sequence
# =============================================================================

@dataclass(frozen=True, slots=True)
class ProcessedSequence:
    """
    Metadata describing one compiled sequence.

    Parameters
    ----------
    sequence_name
        Name of the sequence.

    num_frames
        Number of processed frames.

    frames
        Metadata for every processed frame.

    objects
        Metadata for every tracked object.
    """

    sequence_name: str

    num_frames: int

    frames: tuple[ProcessedFrame, ...]

    objects: dict[int, ProcessedObject]